export type ImageEmote = { key: string; path: string };

export const IMAGE_EMOTES: ImageEmote[] = [
  { key: '5Head',          path: '/emotes/5Head.webp' },
  { key: 'Aware',          path: '/emotes/Aware.webp' },
  { key: 'Awkward',        path: '/emotes/Awkward.webp' },
  { key: 'AYAYA',          path: '/emotes/AYAYA.webp' },
  { key: 'BASED',          path: '/emotes/BASED.webp' },
  { key: 'BatmanHmmm',     path: '/emotes/BatmanHmmm.webp' },
  { key: 'Bedge',          path: '/emotes/Bedge.webp' },
  { key: 'BONK',           path: '/emotes/BONK.webp' },
  { key: 'catJam',         path: '/emotes/catJam.webp' },
  { key: 'Cinema',         path: '/emotes/Cinema.webp' },
  { key: 'Clap',           path: '/emotes/Clap.webp' },
  { key: 'clubPls',        path: '/emotes/clubPls.webp' },
  { key: 'confusedCat',    path: '/emotes/confusedCat.webp' },
  { key: 'COPIUM',         path: '/emotes/COPIUM.webp' },
  { key: 'ddHuh',          path: '/emotes/ddHuh.webp' },
  { key: 'Deadge',         path: '/emotes/Deadge.webp' },
  { key: 'Donkeykong',     path: '/emotes/Donkeykong.webp' },
  { key: 'DonoWall',       path: '/emotes/DonoWall.webp' },
  { key: 'EZ',             path: '/emotes/EZ.webp' },
  { key: 'gachiBASS',      path: '/emotes/gachiBASS.webp' },
  { key: 'gachiHyper',     path: '/emotes/gachiHyper.webp' },
  { key: 'gachiPRIDE',     path: '/emotes/gachiPRIDE.webp' },
  { key: 'GIGACHAD',       path: '/emotes/GIGACHAD.webp' },
  { key: 'GOLD',           path: '/emotes/GOLD.webp' },
  { key: 'HUHH',           path: '/emotes/HUHH.webp' },
  { key: 'jjkStress',      path: '/emotes/jjkStress.webp' },
  { key: 'KEKW',           path: '/emotes/KEKW.webp' },
  { key: 'KEKWait',        path: '/emotes/KEKWait.webp' },
  { key: 'Kissahomie',     path: '/emotes/Kissahomie.webp' },
  { key: 'LOLL',           path: '/emotes/LOLL.webp' },
  { key: 'LookUp',         path: '/emotes/LookUp.webp' },
  { key: 'LULW',           path: '/emotes/LULW.webp' },
  { key: 'micMUTED',       path: '/emotes/micMUTED.webp' },
  { key: 'MLADY',          path: '/emotes/MLADY.webp' },
  { key: 'modCheck',       path: '/emotes/modCheck.webp' },
  { key: 'MonkaS',         path: '/emotes/MonkaS.webp' },
  { key: 'monkaSteer',     path: '/emotes/monkaSteer.webp' },
  { key: 'monkaTOS',       path: '/emotes/monkaTOS.webp' },
  { key: 'monkaW',         path: '/emotes/monkaW.webp' },
  { key: 'NODDERS',        path: '/emotes/NODDERS.webp' },
  { key: 'NoGodNo',        path: '/emotes/NoGodNo.webp' },
  { key: 'NOPERS',         path: '/emotes/NOPERS.webp' },
  { key: 'NOTED',          path: '/emotes/NOTED.webp' },
  { key: 'NotLikeDuck',    path: '/emotes/NotLikeDuck.webp' },
  { key: 'Oldge',          path: '/emotes/Oldge.webp' },
  { key: 'OMEGALUL',       path: '/emotes/OMEGALUL.webp' },
  { key: 'OOOO',           path: '/emotes/OOOO.webp' },
  { key: 'PartyKirby',     path: '/emotes/PartyKirby.webp' },
  { key: 'PatrickBoo',     path: '/emotes/PatrickBoo.webp' },
  { key: 'peepoClap',      path: '/emotes/peepoClap.webp' },
  { key: 'peepoLeave',     path: '/emotes/peepoLeave.webp' },
  { key: 'PeepoNoob',      path: '/emotes/PeepoNoob.webp' },
  { key: 'peepoPooPoo',    path: '/emotes/peepoPooPoo.webp' },
  { key: 'peepoPride',     path: '/emotes/peepoPride.webp' },
  { key: 'PenguinR',       path: '/emotes/PenguinR.webp' },
  { key: 'pepeD',          path: '/emotes/pepeD.webp' },
  { key: 'Pepega',         path: '/emotes/Pepega.webp' },
  { key: 'PepegaCredit',   path: '/emotes/PepegaCredit.webp' },
  { key: 'PepeHands',      path: '/emotes/PepeHands.webp' },
  { key: 'pepeJAM',        path: '/emotes/pepeJAM.webp' },
  { key: 'PepeLaugh',      path: '/emotes/PepeLaugh.webp' },
  { key: 'PepeSoldier',    path: '/emotes/PepeSoldier.webp' },
  { key: 'pepoClown',      path: '/emotes/pepoClown.webp' },
  { key: 'PETTHEPEEPO',    path: '/emotes/PETTHEPEEPO.webp' },
  { key: 'pikaOMG',        path: '/emotes/pikaOMG.webp' },
  { key: 'POGGERS',        path: '/emotes/POGGERS.webp' },
  { key: 'POLICE',         path: '/emotes/POLICE.webp' },
  { key: 'ppDrool',        path: '/emotes/ppDrool.webp' },
  { key: 'Prayge',         path: '/emotes/Prayge.webp' },
  { key: 'pressF',         path: '/emotes/pressF.webp' },
  { key: 'RainbowPls',     path: '/emotes/RainbowPls.webp' },
  { key: 'Sadge',          path: '/emotes/Sadge.webp' },
  { key: 'Saved',          path: '/emotes/Saved.webp' },
  { key: 'sinisterPatrick',path: '/emotes/sinisterPatrick.webp' },
  { key: 'Smoge',          path: '/emotes/Smoge.webp' },
  { key: 'ThisIsFine',     path: '/emotes/ThisIsFine.webp' },
  { key: 'veryCat',        path: '/emotes/veryCat.webp' },
  { key: 'WeSmart',        path: '/emotes/WeSmart.webp' },
];

export const IMAGE_EMOTE_MAP: Record<string, string> = Object.fromEntries(
  IMAGE_EMOTES.map(e => [e.key, e.path])
);

